language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t maswerty94/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true maswerty94/react-test npm test

after_success:
  - docker build -t maswerty94/multi-client ./client
  - docker build -t maswerty94/multi-nginx ./nginx
  - docker build -t maswerty94/multi-server ./server
  - docker build -t maswerty94/multi-worker ./worker
  #login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #take those images and push them to docker hub
  - docker push maswerty94/multi-client
  - docker push maswerty94/multi-nginx
  - docker push maswerty94/multi-server
  - docker push maswerty94/multi-worker