language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t maswerty/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true maswerty/react-test npm test

after_success:
  - docker build -t maswerty/multi-client ./client
  - docker build -t maswerty/multi-nginx ./nginx
  - docker build -t maswerty/multi-server ./server
  - docker build -t maswerty/multi-worker ./worker
  #login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #take those images and push them to docker hub
  - docker push maswerty/multi-client
  - docker push maswerty/multi-nginx
  - docker push maswerty/multi-server
  - docker push maswerty/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'multi-docker'
  env: 'Multidocker-env'
  bucket_name: 'elasticbeanstalk-us-east-2-118197249705'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY